# Generated by Django 2.2.3 on 2020-02-14 09:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artistid', models.AutoField(primary_key=True, serialize=False)),
                ('artistname', models.CharField(default='artist', max_length=50)),
                ('songcount', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/artist/')),
                ('sampleaudio', models.FileField(blank=True, default='', null=True, upload_to='sample/')),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Songtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/songtype/')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tourid', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(default='-', max_length=30)),
                ('date', models.DateField()),
                ('day', models.CharField(default='-', max_length=10)),
                ('eventname', models.CharField(default='-', max_length=50)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('address', models.CharField(default='', max_length=100)),
                ('tourimage', models.ImageField(blank=True, default='', null=True, upload_to='images/tour/')),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Songgenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/songgenre/')),
                ('songtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Songtype')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('songid', models.AutoField(primary_key=True, serialize=False)),
                ('songname', models.CharField(default='song', max_length=200)),
                ('songlength', models.IntegerField(default=0)),
                ('document', models.FileField(blank=True, default='', null=True, upload_to='document/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Artist')),
                ('songgenre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Songgenre')),
                ('songtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Songtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Muser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.IntegerField(default=0)),
                ('lcount', models.IntegerField(default=0)),
                ('isadmin', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='muser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Muser'),
        ),
        migrations.AddField(
            model_name='artist',
            name='songtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Songtype'),
        ),
    ]
