# Generated by Django 2.2.3 on 2020-02-02 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='time',
        ),
    ]
