# Generated by Django 2.2.3 on 2020-02-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_tour_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muser',
            name='category',
        ),
        migrations.AddField(
            model_name='artist',
            name='sampleaudio',
            field=models.FileField(blank=True, default='', null=True, upload_to='sample/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
