# Generated by Django 2.2.3 on 2020-02-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_tour_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/tour/'),
        ),
    ]
