# Generated by Django 2.2.3 on 2020-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_tour_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='muser',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/user/'),
        ),
    ]
