# Generated by Django 2.2.3 on 2020-02-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_tour_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='image',
            new_name='tourimage',
        ),
    ]
