# Generated by Django 2.2.3 on 2020-02-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20200203_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tourimage',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/tourimage/'),
        ),
    ]
