# Generated by Django 2.2.3 on 2020-02-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20200204_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artistname',
            field=models.CharField(default='artist', max_length=50),
        ),
    ]
