# Generated by Django 2.2.3 on 2020-02-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20200206_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='songtype',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/songtype/'),
        ),
    ]
