# Generated by Django 2.2.3 on 2020-02-06 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_songtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='songgenre',
            name='songtype',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='music.Songtype'),
            preserve_default=False,
        ),
    ]
